### ISSUE TITLE
Keeps downloading the first page

### ISSUE THREAD

**Issue by hamensman** [opemvbs/archiveOrgImageDownloader#1]
I've done all the steps. The book I found has 296 pages. But when I run the script, it downloads the first page (front cover) 296 times.

**Comment by dhavalsavalia** [comment]
Hey did you find any solution?

**Comment by rubberychicken** [comment]
The same thing happens for me. Running in windows.

**Comment by sollrakc** [comment]
I'm having the same problem as well

**Comment by opemvbs** [comment]
archive.org has disabled the iteration method, so there will be no updates or fix to this repository, thanks.
